apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
configMapGenerator:
  - name: 82161846-configmap
    files:
      - application.yml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
images:
  - name: cepgstapacr.azurecr.io/82161846
    newTag: "202409130344"
